name: VPS Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy deploy script to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: 'deploy.sh'
          target: '~/'
